### ISSUE TITLE
Fix PathTooLongException while watching a directory which just ran npm install

### ISSUE THREAD

**Issue by giggio** [aspnet/FileSystem#115]
If you leave dnx running, let's say `dnx . web`, and `npm install`, you are likely to get a `PathTooLongException`. Here is the stack trace:

````
Unhandled Exception: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at Microsoft.AspNet.FileProviders.PhysicalFilesWatcher.OnFileSystemEntryChange(String fullPath)
   at Microsoft.AspNet.FileProviders.PhysicalFilesWatcher.OnChanged(Object sender, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.OnCreated(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.IOCompletionCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
````

**Comment by muratg** [comment]
Dotnet team is working on a fix in CoreCLR for PathTooLong issues. Unfortunately, there's not much we can do on ASP.NET side.  Closing this one.

**Comment by muratg** [comment]
Please refer to: https://www.youtube.com/watch?v=lpa2OFauASM
