### ISSUE TITLE
Microsoft.AspNet.FileProviders.Physical.Tests tests fail on CoreCLR on Linux

### ISSUE THREAD

**Issue by cesarbs** [aspnet/FileSystem#134]
info: Exec
    info:   program: /usr/bin/env
    info:   commandline: bash -c ". \"/home/cesars/src/aspnet/universe/FileSystem/packages/KoreBuild/build/dnvm.sh\"; dnvm run default -runtime coreclr test"
    info:   workingdir: test/Microsoft.AspNet.FileProviders.Physical.Tests
    xUnit.net DNX Runner (64-bit DNXCore 5.0)
      Discovering: Microsoft.AspNet.FileProviders.Physical.Tests
      Discovered:  Microsoft.AspNet.FileProviders.Physical.Tests
      Starting:    Microsoft.AspNet.FileProviders.Physical.Tests
          Assert.False() Failure
          Expected: False
          Actual:   True
          Stack Trace:
               at Microsoft.AspNet.FileProviders.PhysicalFileProviderTests.Exists_WithHiddenFile_ReturnsFalse()
               at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
               at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
               at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
          Assert.False() Failure
          Expected: False
          Actual:   True
          Stack Trace:
               at Microsoft.AspNet.FileProviders.PhysicalFileProviderTests.Token_For_Null_Empty_Whitespace_Filters()
               at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
               at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
               at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
          Assert.False() Failure
          Expected: False
          Actual:   True
          Stack Trace:
               at Microsoft.AspNet.FileProviders.PhysicalFileProviderTests.<Tokens_NotFired_For_FileNames_Starting_With_Period_And_Hidden_Files>d__24.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          Assert.Equal() Failure
          Expected: 1
          Actual:   0
          Stack Trace:
               at Microsoft.AspNet.FileProviders.PhysicalFileProviderTests.<Tokens_With_Path_Ending_With_Slash>d__17.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      Finished:    Microsoft.AspNet.FileProviders.Physical.Tests
    === TEST EXECUTION SUMMARY ===
       Microsoft.AspNet.FileProviders.Physical.Tests  Total: 24, Errors: 0, Failed: 4, Skipped: 0, Time: 5.606s

**Comment by cesarbs** [comment]
This affects https://github.com/aspnet/Universe/issues/304.

**Comment by muratg** [comment]
@cesarbs Can you do the initial investigation?
