### ISSUE TITLE
NotSupportedException for URLs with special characters

### ISSUE THREAD

**Issue by Tratcher** [aspnet/FileSystem#137]
Moved from http://katanaproject.codeplex.com/workitem/430

The static file middleware raises an exception when the input URL contains a character that is valid for HTTP but not authorized on a local path. Example: '/test:character' (note the colon). 
```
      System.NotSupportedException: The given path's format is not supported.
         at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
         at Microsoft.AspNet.FileProviders.PhysicalFileProvider.GetFullPath(String path)
         at Microsoft.AspNet.FileProviders.PhysicalFileProvider.GetDirectoryContents(String subpath)
         at Microsoft.AspNet.StaticFiles.DefaultFilesMiddleware.Invoke(HttpContext context) in C:\git\Universe\StaticFiles\src\Microsoft.AspNet.StaticFiles\DefaultFilesMiddleware.cs:line 66
         at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Server.WebListener.MessagePump.<ProcessRequestAsync>d__23.MoveNext()
```

PhysicalFileProvider.GetDirectoryContents should not throw in this scenario.

**Comment by muratg** [comment]
@BrennanConroy Another repo :)

**Comment by BrennanConroy** [comment]
158dc437a9db16405436f533f6bd428d6820bc9c
